### ISSUE TITLE
タブバーアイコン名称を変更

### ISSUE THREAD

**Issue by ryotaman** [zazensweet/swifttest#2]
First -> Facebook
Secound -> Twitter
Item -> 設定

実装が出来たらPUSH後にコメントして下さい。

**Comment by zazensweet** [comment]
Xcode右側にあるエリアのBar ItemからTitleに対して名前を変更しました。

**Comment by ryotaman** [comment]
確認出来ました :+1: 
各ビューのアイコン下部名称部分をダブルクリックでも変更することも可能です。
