### ISSUE TITLE
TextFieldの配置

### ISSUE THREAD

**Issue by ryotaman** [zazensweet/swifttest#4]
StoryBordのFirstViewController 内にTextFieldを配置し、
常に中央になるようオートレイアウトを設定

* TextFieldの表示サイズを変更
* 高さを変更

実装が出来たらPUSH後にコメントして下さい。

**Comment by zazensweet** [comment]
Xcode右下のAlignで中央にして、PinでTextFieldのサイズを固定にしました。

**Comment by ryotaman** [comment]
TextFieldの配置、オートレイアウトの設定がされていること確認出来ました！ :+1:
