### ISSUE TITLE
TextField内容をUILabelに反映

### ISSUE THREAD

**Issue by ryotaman** [zazensweet/swifttest#5]
FirstViewController.swiftで
TextFieldに入力された文字を先ほど設定したUILabelにリアルタイムに反映させる

実装が出来たらPUSH後にコメントして下さい。

**Comment by zazensweet** [comment]
TextFieldに
@IBOutletと@IBActionのふたつを適用しました。
Edit Changedでリアルタイムにラベルに反映されるようにしました。

**Comment by ryotaman** [comment]
リアルタイムに変更が反映され、表示されている事が確認出来ました :+1:
