### ISSUE TITLE
キーボードに隠れない

### ISSUE THREAD

**Issue by ryotaman** [zazensweet/swifttest#7]
TextFieldの表示位置を画面の一番下に配置し、
キーボードがせり上がって来てもTextFieldが隠れないようにする

実装が出来たらPUSH後にコメントして下さい。

**Comment by zazensweet** [comment]
最後、ここにきて、急に難しくなりましたw

**Comment by ryotaman** [comment]
キーボードの高さがプログラムから取得できるので、
その高さ分Viewの位置をずらすことで実現出来るかと思います。

**Comment by zazensweet** [comment]
ネットや本の見様見真似で、何とか実現できました。
ViewにScrollViewを置いてまたViewを置いて、、、みたいな概念だけ理解できました。
コードについては、まだどれが何の処理をしているか把握できていません。

**Comment by ryotaman** [comment]
徐々に理解していくようにしましょう！
