### ISSUE TITLE
文字数制限

### ISSUE THREAD

**Issue by ryotaman** [zazensweet/swifttest#8]
文字数制限をかけてみましょう

TextFieldに11文字以上のテキストが入力された場合
TextFieldの枠線を赤く
10文字以下の場合は黒くなるよう実装してみてください。

**Comment by zazensweet** [comment]
characters.countで文字数を取得し、if文でテキストフィールドの枠色を振り分けました。
型を変更させるところでつまりました。キャストさせることは理解しましたが、
文字数の値をStringからIntにしているつもりなのですが、、、コード上でオプションを押しながら調べるとDistanceと表示されて、ちょっと謎でした。

**Comment by ryotaman** [comment]
確かにDistanceですね。。
距離、長さと言った感じの意味でしょうか。
ちょっと気になったので、自分も見てみましたが、
```
testTextField.text!.characters.count
```
の時点でINTが返って来ていますね。
また、 countTF もINTとなっています。

文字数取れて、文字制限がかかっていること確認出来ました！ :+1:
